#!/bin/sh
show(){
    echo ""
    if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
        updates_arch=0
    fi
    if ! updates_aur=$(paru -Qum 2> /dev/null | wc -l); then
        updates_aur=0
    fi

    updates=$((updates_arch + updates_aur))

    if [ "$updates" -gt 0 ]; then
        echo "%{F#F0C674} %{F-}$updates"
    else
        echo ""
    fi
}
update(){
    polybar-msg action "#paru.hook.0"
    echo "sending command to polybar"
}
supdate(){
   echo "sending command to polybar"
   machinectl -q shell "james@" /usr/bin/bash -c 'polybar-msg action "#paru.hook.0"'&
}

case "$1" in
    --update)
        update
        ;;
    --supdate)
	supdate
	;;
    *)
        show
        ;;
esac
